// Copyright 2024 Santosh Kumar (@santosh)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define TRI_LAYER_LOWER_LAYER 3
#define TRI_LAYER_UPPER_LAYER 4
#define TRI_LAYER_ADJUST_LAYER 5

#define ENCODER_A_PINS { F5 }
#define ENCODER_B_PINS { F4 }
#define ENCODER_RESOLUTIONS { 4 }
#define ENCODER_A_PINS_RIGHT { F4 }
#define ENCODER_B_PINS_RIGHT { F5 }
#define ENCODER_RESOLUTIONS_RIGHT { 4 }

#define OLED_TIMEOUT 30000
#define OLED_FADE_OUT
#define OLED_FADE_OUT_INTERVAL 10
//#define OLED_SCROLL_TIMEOUT 10000

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define SPLIT_WPM_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_LAYER_STATE_ENABLE

#define SPLIT_TRANSACTION_IDS_KB KEYBOARD_SYNC_A

#define NO_AUTO_SHIFT_SPECIAL
#define AUTO_SHIFT_TIMEOUT 250
#define RETRO_SHIFT 500

#define TAPPING_TERM 200 // Impossible to trigger, set to 175 for dot space use

#define MOUSEKEY_MAX_SPEED 3
#define MOUSEKEY_INTERVAL 6
#define MOUSEKEY_TIME_TO_MAX 80
#define MOUSEKEY_MOVE_DELTA 4
